openapi: 3.0.0
info:
  title: Surveillance Info
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '':
    get:
      summary: GET image url from Google Drive
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  required:
                    - created_at
                    - drive_folder_id
                    - image_url
                  properties:
                    created_at:
                      type: string
                      minLength: 1
                    drive_folder_id:
                      type: string
                      minLength: 1
                    image_url:
                      type: string
                      minLength: 1
                x-examples:
                  example-1:
                    - created_at: '2021-12-13T02:23:05.000Z'
                      drive_folder_id: 1_5x9Cz-3VmX_r3igi0KMbl7TtQwBCDsf
                      image_url: a
                    - created_at: '2021-12-13T02:23:42.643Z'
                      drive_folder_id: 1_5x9Cz-3VmX_r3igi0KMbl7TtQwBCDsf
                      image_url: a
                    - created_at: '2021-12-13T02:26:39.111Z'
                      drive_folder_id: 1_5x9Cz-3VmX_r3igi0KMbl7TtQwBCDsf
                      image_url: a
              examples:
                example:
                  value:
                    - created_at: string
                      drive_folder_id: string
                      image_url: string
                    - created_at: string
                      drive_folder_id: string
                      image_url: string
                    - created_at: string
                      drive_folder_id: string
                      image_url: string
      operationId: get-image-url
      parameters:
        - schema:
            type: boolean
          in: query
          name: api
    parameters: []
    post:
      summary: Add image to Google Drive
      operationId: post-image-to-gas
      parameters:
        - schema:
            type: string
          in: query
          name: data
          description: base64 image data
          required: true
      responses:
        '200':
          description: OK
      description: base64にエンコードされたデータをPOSTするとGoogle Driveに保存される
components:
  schemas: {}
